"""Add department foreign key to team model

Revision ID: 669cd35e8c2f
Revises: dfb2ddf9f301
Create Date: 2025-04-20 19:59:41.120090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669cd35e8c2f'
down_revision: Union[str, None] = 'dfb2ddf9f301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('dept_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_teams_dept_id'), 'teams', ['dept_id'], unique=False)
    op.create_foreign_key(op.f('fk_teams_dept_id_departments'), 'teams', 'departments', ['dept_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_teams_dept_id_departments'), 'teams', type_='foreignkey')
    op.drop_index(op.f('ix_teams_dept_id'), table_name='teams')
    op.drop_column('teams', 'dept_id')
    # ### end Alembic commands ###
