"""Add project_participants association table

Revision ID: dc1a3f0aa2bd
Revises: 669cd35e8c2f
Create Date: 2025-04-21 22:22:42.203875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1a3f0aa2bd'
down_revision: Union[str, None] = '669cd35e8c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_participants',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_participants_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_participants_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('pk_project_participants'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_participants')
    # ### end Alembic commands ###
