services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000" # Expose backend on host port 8001
    volumes:
      # Only map necessary directories for development
      - ./backend/app:/app/app
      - ./backend/scripts:/app/scripts
      - ./backend/alembic.ini:/app/alembic.ini
      # Use a named volume for the venv to prevent overwriting
      - backend_venv:/app/.venv
    env_file:
      - ./.env # Use consolidated environment file
    environment:
      - RUNNING_IN_DOCKER=true
      # Enable spatial features since we're using PostGIS now
      - USE_SPATIAL_FEATURES=true
      - BYPASS_DB_FOR_DEMO=false
    depends_on:
      - db
    # Add health check for backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    # Run only the initial migration to create tenant tables
    command: >
      bash -c "pip install networkx &&
              alembic upgrade 12819ed4b9bd &&
              uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    # Add resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  db:
    image: postgres:15-alpine # Use official PostgreSQL Alpine image for simplicity
    platform: linux/arm64/v8  # Match your host platform
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata # Different mount path
    ports:
      - "5433:5432" # Expose DB on host port 5433 (avoid conflict with local install)
    # Enhanced configuration merged from override file
    command: >
      bash -c "
        mkdir -p /var/lib/postgresql/data/pgdata &&
        echo 'host all all all md5' >> /var/lib/postgresql/data/pgdata/pg_hba.conf &&
        echo 'local all all md5' >> /var/lib/postgresql/data/pgdata/pg_hba.conf &&
        docker-entrypoint.sh postgres
      "
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-knowledgeplan_dev}
      PGDATA: /var/lib/postgresql/data/pgdata # Set PGDATA to match volume mount
    restart: unless-stopped
    # Add resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Expose frontend on host port 5173
    volumes:
      # Mount source code for development
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    env_file:
      - ./.env # Use consolidated environment file
    command: npm run dev -- --host
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  postgres_data: # Define the volume for data persistence 
  backend_venv: # Define the named volume for the virtual environment