"""Add activity_logs table

Revision ID: 715852b65460
Revises: a9c625da9ca5
Create Date: 2025-04-26 19:36:53.946896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715852b65460'
down_revision: Union[str, None] = 'a9c625da9ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_entity_type', sa.String(), nullable=True),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_activity_logs_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_target_entity_id'), 'activity_logs', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_target_entity_type'), 'activity_logs', ['target_entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_tenant_id'), 'activity_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.drop_index('ix_edges_src', table_name='edges')
    op.create_index(op.f('ix_edges_src'), 'edges', ['src'], unique=False)
    op.create_index(op.f('ix_edges_tenant_id'), 'edges', ['tenant_id'], unique=False)
    op.create_foreign_key(op.f('fk_edges_tenant_id_tenants'), 'edges', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_nodes_tenant_id_tenants'), 'nodes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_nodes_tenant_id_tenants'), 'nodes', type_='foreignkey')
    op.drop_constraint(op.f('fk_edges_tenant_id_tenants'), 'edges', type_='foreignkey')
    op.drop_index(op.f('ix_edges_tenant_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_src'), table_name='edges')
    op.create_index('ix_edges_src', 'edges', ['tenant_id', 'src'], unique=False)
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_tenant_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_target_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_target_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
