"""Add team model and relationship to user

Revision ID: 016f196dbf5a
Revises: 536eff702d85
Create Date: 2025-04-13 20:03:01.545634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016f196dbf5a'
down_revision: Union[str, None] = '536eff702d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_teams_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    # op.add_column('users', sa.Column('team_id', sa.UUID(), nullable=True)) # Commented out: Column likely already exists
    op.alter_column('users', 'manager_id',
               existing_type=sa.UUID(),
               nullable=True)
    # This alter_column should now handle the existing column correctly
    op.alter_column('users', 'team_id',
               existing_type=sa.VARCHAR(), # Assuming previous type was VARCHAR/String
               type_=sa.UUID(as_uuid=True), 
               existing_nullable=True,
               postgresql_using='team_id::uuid') 
    op.create_foreign_key(op.f('fk_users_team_id_teams'), 'users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_team_id_teams'), 'users', type_='foreignkey')
    op.alter_column('users', 'team_id',
               existing_type=sa.UUID(as_uuid=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
