"""Add new knowledge asset types

Revision ID: f5081054e612
Revises: 2d117f7393a2
Create Date: 2025-04-20 00:31:48.850793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5081054e612'
down_revision: Union[str, None] = '2d117f7393a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the enum type with ALL desired values
new_enum_values = ('NOTE', 'DOCUMENT', 'MESSAGE', 'MEETING', 'REPORT', 'SUBMISSION', 'PRESENTATION')
old_enum_values = ('NOTE', 'DOCUMENT', 'MESSAGE', 'MEETING')

enum_name = 'knowledgeassettypeenum'
table_name = 'knowledge_assets'
column_name = 'type'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute(f"ALTER TYPE {enum_name} ADD VALUE 'REPORT'")
    # op.execute(f"ALTER TYPE {enum_name} ADD VALUE 'SUBMISSION'")
    # op.execute(f"ALTER TYPE {enum_name} ADD VALUE 'PRESENTATION'")
    # op.alter_column('knowledge_assets', 'type',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.drop_index('ix_knowledge_assets_project_id', table_name='knowledge_assets')
    # op.drop_index('ix_knowledge_assets_tenant_id', table_name='knowledge_assets')
    # op.drop_index('ix_knowledge_assets_title', table_name='knowledge_assets')
    # op.drop_index('ix_knowledge_assets_type', table_name='knowledge_assets')
    # ### end Alembic commands ###

    # Manual approach: Drop and recreate the enum
    op.execute(f"ALTER TABLE {table_name} ALTER COLUMN {column_name} TYPE VARCHAR")
    op.execute(f"DROP TYPE {enum_name}")
    new_enum = sa.Enum(*new_enum_values, name=enum_name)
    new_enum.create(op.get_bind(), checkfirst=False)
    op.execute(f"ALTER TABLE {table_name} ALTER COLUMN {column_name} TYPE {enum_name} USING {column_name}::{enum_name}")
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_knowledge_assets_type', 'knowledge_assets', ['type'], unique=False)
    # op.create_index('ix_knowledge_assets_title', 'knowledge_assets', ['title'], unique=False)
    # op.create_index('ix_knowledge_assets_tenant_id', 'knowledge_assets', ['tenant_id'], unique=False)
    # op.create_index('ix_knowledge_assets_project_id', 'knowledge_assets', ['project_id'], unique=False)
    # op.alter_column('knowledge_assets', 'type',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # ### end Alembic commands ###

    # Manual approach: Revert to the old enum
    # Note: This might fail if data with the new enum values exists!
    op.execute(f"ALTER TABLE {table_name} ALTER COLUMN {column_name} TYPE VARCHAR")
    op.execute(f"DROP TYPE {enum_name}")
    old_enum = sa.Enum(*old_enum_values, name=enum_name)
    old_enum.create(op.get_bind(), checkfirst=False)
    op.execute(f"ALTER TABLE {table_name} ALTER COLUMN {column_name} TYPE {enum_name} USING {column_name}::{enum_name}")
